version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:stable
    environment:
      EULA: "true"
      TYPE: "PAPER"
      ONLINE_MODE: "false"
      ICON: "https://static.wikia.nocookie.net/vsbattles/images/b/b6/Yveltal.png/revision/latest?cb=20180428232050"
      MOTD: "§9Xerneas§7, §4Yveltal§7, and §2Zygarde§7 are cool!"
      OPS: |
        hahehyhu
      EXISTING_OPS_FILE: MERGE
      MEMORY: "4G"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      SPIGET_RESOURCES: "2124,19254"
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - "mc:/data"
    restart: always

volumes:
  mc: {}
